export const dummyProducts = [
  {
    id: 1,
    name: "Product 1",
    sold: 100,
    label: "New",
    price: 50,
    category: "Drinks",
    coverUrl: "/assets/images/product-1.jpg",
    priceSale: 45,
    ratingNumber: 4.5,
  },
  {
    id: 2,
    name: "Product 2",
    sold: 50,
    label: "Sale",
    price: 30,
    category: "Food",
    coverUrl: "/assets/images/product-3.jpeg",
    priceSale: 25,
    ratingNumber: 3.8,
  },
  {
    id: 3,
    name: "Product 3",
    sold: 75,
    label: "New",
    price: 80,
    category: "Drinks",
    coverUrl: "/assets/images/product-2.jpeg",
    priceSale: 75,
    ratingNumber: 4.2,
  },
];
