import "./globals.css";
import PropTypes from "prop-types";
// import ThemeRegistry from "@/theme/ThemeRegistry";
// import { ModeProvider } from "@/context/ThemeContext";
import { primaryFont } from "@/theme/typography";
import { LocalizationProvider } from "@/locales";
import ProgressBar from "@/components/partials/ProgressBar";
import ThemeProvider from "@/theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <LocalizationProvider>
          <ThemeProvider>
            <ProgressBar />
            {children}
          </ThemeProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node,
};
