import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { ModeProvider } from "@/context/ThemeContext";
import { getServerSession } from "next-auth";

import SessionProvider from "../context/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ModeProvider>
            <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
          </ModeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
